---
- name: Ubuntu - Upgrade all packages to the latest version
  become: true
  apt:
    name: "*"
    state: latest
    update_cache: true
    force_apt_get: true
  register: run_apt_update
  until: run_apt_update is not failed
  retries: 5
  delay: 30

- name: Ubuntu - Ensure convenient tools installed
  become: true
  apt:
    name: "{{ packages }}"
    force_apt_get: true
  vars:
    packages:
      - vim
      - patch
      - diffstat
      - git
      - bridge-utils
      - util-linux
      - build-essential
      - git-buildpackage
      - pristine-tar
      - sbuild
      - debhelper
      - ubuntu-dev-tools
      - piuparts
      - haveged
      - schroot
      - apt-cacher-ng
  register: run_apt_install
  until: run_apt_install is not failed
  retries: 5
  delay: 30

- name: Ubuntu - Configure apt-cacher
  become: true
  template:
    src: 10acng.j2
    dest: /etc/apt/apt.conf.d/01acng

- name: Ubuntu - Ensure workdirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ubuntu/build
    - ubuntu/logs
    - ubuntu/scratch

- name: Ubuntu - Ensure scratch mount in chroot
  become: true
  lineinfile:
    dest: /etc/schroot/sbuild/fstab
    line: /home/{{ ansible_user }}/ubuntu/scratch /scratch none rw,bind 0 0
    state: present
    create: true

- name: Ubuntu - Ensure sbuild config
  template:
    src: "{{ item }}.j2"
    dest: .{{ item }}
  with_items:
    - mk-sbuild.rc
    - sbuildrc

- name: Ubuntu - Add '{{ ansible_user }}' to group sbuild
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: sbuild
    append: yes
  register: group_added

# NOTE(jangutter): This is the preferred method but our Ansible instance
# raises an internal error. Workaround by rebooting!
#
# - name: Ubuntu - Reset ssh connection to pick up group
#   meta: reset_connection
#   when: group_added is changed

- name: Ubuntu - Reboot to enable new group
  become: true
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  no_log: true
  when: group_added is changed

- name: Ubuntu - Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  no_log: true
  when: group_added is changed

- name: Restart zuul_console daemon.
  include_tasks: restart-zuul-console.yaml
  when: group_added is changed and zuul is defined

- name: Ubuntu - generate GPG keypair
  command: sbuild-update --keygen

- name: Ubuntu - Generate schroot
  command: mk-sbuild {{ distro }} --arch=amd64
